server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: trello-flow-bot
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    schemas: ${FLYWAY_SCHEMA:public}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-migration-naming: true
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${JPA_IS_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
encryption:
  key: ${ENCRYPTION_KEY}
  salt: ${ENCRYPTION_SALT}
app:
  url: ${APP_URL}
trello:
  webhook:
    path: /trello/webhook
  api:
    auth_token:
      expiration: never
    key: ${TRELLO_API_KEY}
    secret: ${TRELLO_API_SECRET}
    path: /oauth/callback
telegram:
  callback:
    expiration: 1m
    cleanup:
      interval.secs: 10
  bot:
    path: bot
    token: ${BOT_TOKEN}