CREATE TABLE users
(
    id               BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    telegram_id      BIGINT       NOT NULL,
    chat_id          BIGINT       NOT NULL,
    state            VARCHAR(255) NOT NULL,
    trello_api_key   VARCHAR(255),
    trello_api_token VARCHAR(255),
    language VARCHAR(255),

    CONSTRAINT pk_users PRIMARY KEY (id)
);