CREATE TABLE trello_models
(
    id            BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(255) NOT NULL,
    model_id      VARCHAR(255) NOT NULL,
    type          VARCHAR(255) NOT NULL,
    url           VARCHAR(255) NOT NULL,
    is_subscribed BOOLEAN      NOT NULL DEFAULT FALSE,
    user_id       BIGINT       NOT NULL,

    CONSTRAINT pk_trello_models PRIMARY KEY (id),
    CONSTRAINT fk_trello_models_on_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE trello_webhooks
(
    id              VARCHAR(255) NOT NULL,
    trello_model_id BIGINT,
    user_id         BIGINT,

    CONSTRAINT pk_trello_webhooks PRIMARY KEY (id),
    CONSTRAINT fk_trello_webhooks_on_trello_model FOREIGN KEY (trello_model_id) REFERENCES trello_models (id),
    CONSTRAINT fk_trello_webhooks_on_user FOREIGN KEY (user_id) REFERENCES users (id)
);