CREATE TABLE board_models
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       TEXT,
    model_id   TEXT,
    url        TEXT,
    subscribed BOOLEAN,
    user_id    BIGINT,
    CONSTRAINT pk_board_models PRIMARY KEY (id)
);

CREATE TABLE list_models
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    model_id       TEXT,
    name           TEXT,
    subscribed     BOOLEAN,
    board_model_id BIGINT,
    CONSTRAINT pk_list_models PRIMARY KEY (id)
);

CREATE TABLE trello_webhooks
(
    id             TEXT   NOT NULL,
    board_model_id BIGINT NOT NULL,
    user_id         BIGINT NOT NULL,

    CONSTRAINT pk_trello_webhooks PRIMARY KEY (id),
    CONSTRAINT fk_trello_webhooks_on_board_model FOREIGN KEY (board_model_id) REFERENCES board_models (id),
    CONSTRAINT fk_trello_webhooks_on_user FOREIGN KEY (user_id) REFERENCES users (id)
);