CREATE TABLE trello_models
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name          TEXT    NOT NULL,
    model_id      TEXT    NOT NULL,
    type          TEXT    NOT NULL,
    url           TEXT,
    is_subscribed BOOLEAN NOT NULL DEFAULT FALSE,
    user_id       BIGINT  NOT NULL,

    CONSTRAINT pk_trello_models PRIMARY KEY (id),
    CONSTRAINT fk_trello_models_on_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE trello_webhooks
(
    id TEXT NOT NULL,
    trello_model_id BIGINT NOT NULL,
    user_id         BIGINT NOT NULL,

    CONSTRAINT pk_trello_webhooks PRIMARY KEY (id),
    CONSTRAINT fk_trello_webhooks_on_trello_model FOREIGN KEY (trello_model_id) REFERENCES trello_models (id),
    CONSTRAINT fk_trello_webhooks_on_user FOREIGN KEY (user_id) REFERENCES users (id)
);